### PR TITLE
Projects search

### PR DESCRIPTION
**Pull request by kaffcop**
題名の検索はできるようになりました。

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi5/151)

### CODE REVIEW

**Comment by hrl7** [comment]
@kaffcop これって完成した？

**Comment by kaffcop** [comment]
@hrl7 直すことはあるかもしれませんが動きます。

**Comment by hrl7** [comment]
@kaffcop  機能として完成したら, 早くmasterにmergeしてしまいたいので, 問題なければmasterにmergeしてしまおう。
もし心配だったら, 俺に@をつけて呼んでくれ, レビューする。
というわけでみてみるー

**Comment by hrl7** [comment]
Reviewed 36 of 45 files at r3, 1 of 1 files at r4, 5 of 10 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/assets/javascripts/client/components/CreateProject.react.js, line 16 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZGcUg6akQgNUdI0ms:-KFZGcUh8Z-OCljypGbB:-1647631300) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/components/CreateProject.react.js#L16)):*
```date_obj``` はどこでも使ってないみたい
あと, jsの命名規則は, 他のに合わせてキャメルケースだと嬉しい。

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 47 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZH2yf1Gj6AgSmMZrl:-KFZH2yg-l6FF9hGIX1W:68055719) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/components/FabnaviApp.react.js#L47)):*
これは, ```window.onload```と同じ。
ページが読み込まれた直後に走る。
ProjectStoreのinitと上で用意れた, ページのroutingをつくってる

---

*[app/assets/javascripts/client/components/Footer.react.js, line 21 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZHjteIrbX_dTdm5AR:-KFZHjteIrbX_dTdm5AS:1899723148) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/components/Footer.react.js#L21)):*
typoしてる?

---

*[app/assets/javascripts/client/components/ProjectList.react.js, line 65 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZIJevee_RRt2nTfsY:-KFZIJevee_RRt2nTfsZ:-663190789) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/components/ProjectList.react.js#L65)):*
インデントがずれてる

---

*[app/assets/javascripts/client/stores/ProjectListStore.js, line 4 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZIZdla9-tPwdbrweq:-KFZIZdla9-tPwdbrwer:-1547241246) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/stores/ProjectListStore.js#L4)):*
キャメルケースにしてくれると助かる
```init_projects => initProjects```

---

*[app/assets/javascripts/client/stores/ProjectListStore.js, line 27 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZIoZ3sQ4qb2JxjYHl:-KFZIoZ3sQ4qb2JxjYHm:1898627367) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/stores/ProjectListStore.js#L27)):*
ここもinitProjects

---

*[app/assets/javascripts/client/stores/ProjectListStore.js, line 82 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZIyl39pEbTZC6LU-0:-KFZIyl39pEbTZC6LU-1:-239436113) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/stores/ProjectListStore.js#L82)):*
```break;``` がない

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 135 \[r6\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFZJQBdu8dB-Fn3OdE3:-KFZJQBdu8dB-Fn3OdE4:1025551672) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c1cc5207c4446ad83e87c2c052b4c03b85f9666c/app/assets/javascripts/client/utils/WebAPIUtils.js#L135)):*
dateという属性は遅れない
詳しくは/api/v1/swaggerで確認してくれ。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151)*

**Comment by kaffcop** [comment]
ありがとうございます。いろいろいじった跡が残ってました。訂正します。

**Comment by hrl7** [comment]
さくさく動いてるし, さっきの修正だけしてくれたらmergeしてしまおう

**Comment by kaffcop** [comment]
修正しました

**Comment by hrl7** [comment]
Reviewed 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 47 \[r7\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151#-KFb4z9WF2yiZMx-Wm42:-KFb4z9WF2yiZMx-Wm43:-1610455740) ([raw file](https://github.com/fabnavi/fabnavi5/blob/8a63f801e47a0f0c5ba5e531aecc9d0ba5ce4aa0/app/assets/javascripts/client/components/FabnaviApp.react.js#L47)):*
ごめん, 俺のコメントがtypoしてた
 ProjectStoreのinitと, 上で定義されたroutesを基に, Reactをdocument.body以下に展開する

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151)*

**Comment by hrl7** [comment]
Reviewed 2 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/151)*

**Pull request merged**
