### PR TITLE
[WIP]Kaffcop add keyscroll

### PR DESCRIPTION
**Pull request by kaffcop**
キースクロールを追加しました。

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi5/157)

### CODE REVIEW

**Comment by hrl7** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 82 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqbMME1piEP6Dgkqm:-KFbqbMNdsJQDZumW414:-1994135604) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L82)):*
2項演算子はスペースを前後にいれるとよい
[JavaScript style guide](https://developer.mozilla.org/ja/docs/JavaScript_style_guide#.E3.83.9B.E3.83.AF.E3.82.A4.E3.83.88.E3.82.B9.E3.83.9A.E3.83.BC.E3.82.B9) 

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 89 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqoD-0GS_Xh1pcWgy:-KFbqoD-0GS_Xh1pcWgz:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L89)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 95 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqqyenpo5R96jilz8:-KFbqqyenpo5R96jilz9:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L95)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 96 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbr5kWTSU29zA8SzBz:-KFbr5kWTSU29zA8SzC-:479620558) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L96)):*
aniだと意味が分からなくなりそうなので, animationTimerとかの方がいいかな

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 97 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqtK1c01oBGRf2538:-KFbqtK1c01oBGRf2539:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L97)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 101 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbquPX4Q_q9WYoYwBG:-KFbquPX4Q_q9WYoYwBH:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L101)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 107 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqvoervTRhMd7nzlF:-KFbqvoervTRhMd7nzlG:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L107)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 109 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqwW_lGPQckyaHzMD:-KFbqwW_lGPQckyaHzME:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L109)):*
white space

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 113 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KFbqxSo4a51vxwWbtCJ:-KFbqxSo4a51vxwWbtCK:725701674) ([raw file](https://github.com/fabnavi/fabnavi5/blob/f525de771ba93f4909a3069601defff0611c3ff2/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L113)):*
white space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157)*

**Comment by kaffcop** [comment]
space入れました

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157)*

**Comment by hrl7** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 98 \[r3\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KGBq2cKpwXccG26G1t6:-KGBq2cL1QBuUPJ7uGOR:814282692) ([raw file](https://github.com/fabnavi/fabnavi5/blob/fe690680acc239b07861bab1f79e186dd2681e8a/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L98)):*
これもanimationTimerにしないといけない

---

*[app/assets/javascripts/client/stores/ProjectSelectorStore.js, line 113 \[r3\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157#-KGBq7hwlQEiH8AM9vFC:-KGBq7hwlQEiH8AM9vFD:1334825571) ([raw file](https://github.com/fabnavi/fabnavi5/blob/fe690680acc239b07861bab1f79e186dd2681e8a/app/assets/javascripts/client/stores/ProjectSelectorStore.js#L113)):*
セミコロンの前にはスペースをいれない

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157)*

**Comment by hrl7** [comment]
@kaffcop コンフリクトしてるのでmasterをrebaseなりmergeなりしてくれると助かる

**Comment by kaffcop** [comment]
修正　mergeしました

**Comment by hrl7** [comment]
@kaffcop ``` $ npm run lint ```しよう

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157)*

**Comment by kaffcop** [comment]
修正しました

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/157)*

**Pull request merged**
