### PR TITLE
Add github user-icon

### PR DESCRIPTION
**Pull request by ysmr**
project listのユーザーアイコンがgithubのアイコンで表示されるようにしました

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi5/177)

### CODE REVIEW

**Comment by hrl7** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/assets/javascripts/client/components/ProjectElement.react.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177#-KGbaHhNlFocnlBjeFRw:-KGbaHhNlFocnlBjeFRx:-217161684) ([raw file](https://github.com/fabnavi/fabnavi5/blob/33eaa1425642d70cf24cf30760486892cb8ebd25/app/assets/javascripts/client/components/ProjectElement.react.js#L41)):*
キャメルケースしよう

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177)*

**Comment by ysmr** [comment]
キャメルケースしました！

**Comment by hrl7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/assets/javascripts/client/components/ProjectElement.react.js, line 41 \[r2\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177#-KGgf0M1ou8BSwikqlAL:-KGgf0M2cMY_IxIQmOyh:831842001) ([raw file](https://github.com/fabnavi/fabnavi5/blob/a3cefa54643f168f0bd330ee5f1a2f7a4fb16fae/app/assets/javascripts/client/components/ProjectElement.react.js#L41)):*
それはPascalCaseっていうんだ。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177)*

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177)*

**Comment by ysmr** [comment]
あ、すみません… 直しました！

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/177)*

**Pull request merged**
