### PR TITLE
[WIP] Ysmr GitHub auth

### PR DESCRIPTION
**Pull request by ysmr**
やり直してサインアウトのところをやっています

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi5/158)

### CODE REVIEW

**Comment by hrl7** [comment]
```git push -f```は気をつけて使ってね

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd0NGZmaerRwkoAuNq:-KFd0NG_7S5K-mbm2c3f:-1905751836) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/components/FabnaviApp.react.js#L15)):*
使わなければ, コメントアウトでなく, 消すといい

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 50 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd1MMw1xhvEOE2LMdf:-KFd1MMw1xhvEOE2LMdg:207946529) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/components/FabnaviApp.react.js#L50)):*
この辺のURLをチェックして, client_idとかuidとかaccess_tokenを抽出する機能は, window.onloadの中ではなくて, WebAPIUtilsに入れた方が, 管理しやすい気がする

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 61 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd0bMZV35aLCU7npiz:-KFd0bMZV35aLCU7npj-:-1844258178) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/components/FabnaviApp.react.js#L61)):*
コメントアウトは消そう

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 26 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd1pkOgpuK4ZWVNqwr:-KFd1pkP2ULMkP6XxxVt:2119775451) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/utils/WebAPIUtils.js#L26)):*
[JSON.parseはエラーする](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Throws) ので, tryでくくっておきたい

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 291 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd12eknqPsTh9e7fA7:-KFd12eknqPsTh9e7fA8:304921467) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/utils/WebAPIUtils.js#L291)):*
hostは本番だと変わるので, 192.168.33.10:3000を固定じゃなくて, 定数にして切り出してほしい

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by hrl7** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd0NGZmaerRwkoAuNq:-KFd3Nz2iIXLWoxpFliP:-1064474593) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/components/FabnaviApp.react.js#L15)):*
これ, global.onload内で使ってるよ

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 303 \[r1\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFd4Lsz26JD9nmkOmxb:-KFd4Lt-RHIIQJUEHNnN:-1294641608) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c2b7f710359ef1388a79807b9d63968ca90cb504/app/assets/javascripts/client/utils/WebAPIUtils.js#L303)):*
このServerActionCreator.signOutはServerからのresponseを受けて発火するもので, ボタンを押したコールバックで呼ぶべきではない

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by hrl7** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by ysmr** [comment]
すぐに直せそうなところ直しました！JSON.parseのところはまだです

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 52 \[r3\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFgJXnwGl5OsCfb8SCg:-KFgJXnwGl5OsCfb8SCh:381227796) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c4ad114b77de38b3c34a7ba2154bfa7c985200aa/app/assets/javascripts/client/utils/WebAPIUtils.js#L52)):*
getHeaderという関数名なのに, ```window.location.href```をいじってしまうと, 名前と挙動が一致していなくて気持ち悪い
getという名前がついているのに, 何も返さないのもよくない。

getHeaderという名前から考えられる動作は, 
Headerを取得して返すことな気がする

---

*[app/assets/javascripts/client/utils/WebAPIUtils.js, line 304 \[r3\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KFgIt4Ln-yzthjEN8RG:-KFgIt4Ln-yzthjEN8RH:1831257228) ([raw file](https://github.com/fabnavi/fabnavi5/blob/c4ad114b77de38b3c34a7ba2154bfa7c985200aa/app/assets/javascripts/client/utils/WebAPIUtils.js#L304)):*
```url.substring(0, num)```　が2回でてきている。
hostとかそういう名前の変数を用意した方がいいだろう。
numという変数名は数値である事以外意味を持っていない。

リーダブルコードを読みませう

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by hrl7** [comment]
@ysmr reviewしました！

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-:-KFgMCW-gwM0rRjMJM2W:1475603924)*

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by hrl7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[app/assets/javascripts/client/components/FabnaviApp.react.js, line 52 \[r4\]](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158#-KGCqePAXPyii9U_b4Vw:-KGCqePBgpOaofA4Ac7v:1318434819) ([raw file](https://github.com/fabnavi/fabnavi5/blob/7b9541fcfea6e1943490e3de88514db25de38673/app/assets/javascripts/client/components/FabnaviApp.react.js#L52)):*
```SignOut()```ってメソッドが存在しない

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi5/158)*

**Comment by hrl7** [comment]
@ysmr 最新のmasterをfetchしてmergeなりrebaseなりしてくれると助かる

**Pull request closed without merging**
